### ISSUE TITLE
[bug] Could throw exception

### ISSUE THREAD

**Issue by jamdavi** [rido-min/self-describing#1]
https://github.com/rido-min/self-describing/blob/01ee5888b006471821bad58f63273d048ff9b339/device/Program.cs#L15

You should call this inside of the program execution inside of a try/catch. You can then log the specific error.

**Comment by rido-min** [comment]
disagree. This is s pre-req for this sample, and the file will always be there, I dont want to complicate the code with an exception that will never happen. 

Think about that line as a shortcut to avoid inline json.
