### ISSUE TITLE
[style] Consider using more descriptive names

### ISSUE THREAD

**Issue by jamdavi** [rido-min/self-describing#3]
These are a couple of examples where you should use more descriptive names which will help describe what is happening in the sample.

https://github.com/rido-min/self-describing/blob/01ee5888b006471821bad58f63273d048ff9b339/service/Program.cs#L23

https://github.com/rido-min/self-describing/blob/01ee5888b006471821bad58f63273d048ff9b339/service/Program.cs#L44

https://github.com/rido-min/self-describing/blob/01ee5888b006471821bad58f63273d048ff9b339/service/Program.cs#L49

**Comment by rido-min** [comment]
fixed
