### ISSUE TITLE
[suggestion] Don't throw ApplicationException and add a log message

### ISSUE THREAD

**Issue by jamdavi** [rido-min/self-describing#5]
https://github.com/rido-min/self-describing/blob/01ee5888b006471821bad58f63273d048ff9b339/service/Program.cs#L114-L126

Per [these remarks](https://docs.microsoft.com/en-us/dotnet/api/system.applicationexception?view=net-5.0#remarks) you shouldn't throw an application exception. I would suggest InvalidArgument, or InvalidOperation.

Lastly since you're not catching these exceptions it will cause the application to crash and while that definitely ends the execution it's not great to get a callstack with a cryptic message. You should wrap these calls in a try/catch so you can tell the customer why it broke and possibly how to fix it.

**Comment by rido-min** [comment]
>it's not great to get a callstack with a cryptic message
why cryptic? I always prefer a complete stack instead partial information produced by logs in different catch blocks.

Crash, in the context of this sample, is ok. A proper application should decide how to handle those exeption.

I'm changing the exception type to InvalidOperation
