### ISSUE TITLE
[bug] What happens if the hash string is empty?

### ISSUE THREAD

**Issue by jamdavi** [rido-min/self-describing#6]
https://github.com/rido-min/self-describing/blob/01ee5888b006471821bad58f63273d048ff9b339/service/Program.cs#L54-L57

In this snippet we check to make sure the hash is correct, but if it's null I would assume it's not correct or maybe it doesn't exist? If it's a required check you should stop execution if not you should log it at a minimum.

**Comment by rido-min** [comment]
The hash is optional, the application consuming the SDD should decide if accepts the hash or not. If found it should match.
